### ISSUE TITLE
Kafkacat ignores `::` key delimiter.

### ISSUE THREAD

**Issue by uraniumdawn** [edenhill/kafkacat#260] opened 2020-08-07 12:08 UTC
My file `sample.json` with key/message example looks like `customkey::{ "foo": "bar"}`
I use it for producing: `kafkacat -b localhost:9092 -t my-topic -P -K::  -l sample.json` and expect in consumer (`kafkacat -b localhost:9092 -t my-topic -C -f 'Key: %k, Value: %s\n'`) something like this:
`Key: customkey, Value: { "foo": "bar"}`
but get the
 `Key: customkey, Value: :{ "foo": "bar"}`
The additional colon has been appeared:) Looks like kafkacat ignore second colon in `-K::` and split only by first one.
Isn't `::` allowed like a delimiter?

**Comment by edenhill** [comment] 2020-08-18 14:12
The message delimiter is currently limited to one single byte, the extra bytes are ignored.

**Comment by rmoff** [comment] 2020-09-30 16:46
(Duplicate of #140 )

**Closed** 2020-10-08 17:33 UTC
Labels: duplicate

**Comment by qiujiangkun** [comment] 2021-02-20 07:16
This should give a warning

> The message delimiter is currently limited to one single byte, the extra bytes are ignored.
